---
title: "Predict the manner in which exercise is done"
---

### Executive Summary
Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. 

The goal of this project was to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset). 

Using Random Forest Modeling, we got over 99% accuracy on training set of 70% of the total data.



### Exploratory Analysis
#### Data 
The training data for this project are available here: 
https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv
The test data are available here: 
https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv
The data for this project come from this source: http://groupware.les.inf.puc-rio.br/har.

```{r  tidy=FALSE, comment=NA, echo=FALSE, message=FALSE, warning=FALSE}

# install.packages("RCurl")
library(RCurl)
library(caret)

trainingDataURL <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
testDataURL <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"

trainingData <- read.csv(textConnection(getURL(trainingDataURL)), na.strings = c("NA", ""))
testData <- read.csv(textConnection(getURL(trainingDataURL)), na.strings = c("NA", ""))

#clean up data
NAs <- apply(trainingData, 2, function(x) {
  sum(is.na(x))
})

cleanTrainingData <- trainingData[, which(NAs == 0)]
cleanTestData <- testData[, which(NAs == 0)]

summary(cleanTrainingData)
summary(cleanTestData)

##Using 70% for training and 30% for Cross Validation. None generated for testing since that set is already provided.
trainIndex <- createDataPartition(y = cleanTrainingData$classe, p = 0.7, list = FALSE)
trainSet <- cleanTrainingData[trainIndex, ]
crossValidationSet <- cleanTrainingData[-trainIndex, ]
# Removing variables that have time, or names in it, also new_window.
# Columns 1..6
removeIndex <- as.integer(c(1, 2, 3, 4, 5, 6))
trainSet <- trainSet[, -removeIndex]
testSet <- cleanTestData[, -removeIndex]

dim(trainSet)
dim(testSet)
```
#### Data Cleanup


### Machine learning algorithm 
#### Model 
#### Prediction
#### Sample error and cross-validation

### Conclusions

